#ifndef NETWORKMANAGERGLOBAL_H
#define NETWORKMANAGERGLOBAL_H


#include <qglobal.h>

#ifndef NETWORKMANAGER_STATIC
#  ifdef NETWORKMANAGER_LIB
#    define NETWORKMANAGER_EXPORT Q_DECL_EXPORT
#  else
#    define NETWORKMANAGER_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define NETWORKMANAGER_EXPORT
#endif


#endif // NETWORKMANAGERGLOBAL_H
