#ifndef WPA_CTRL_H
#define WPA_CTRL_H

#ifdef  __cplusplus
extern "C" {
#endif

/* wpa_supplicant control interface - fixed message prefixes */

#define WPA_CTRL_REQ "CTRL-REQ-"

#define WPA_CTRL_RSP "CTRL-RSP-"

/* Event messages with fixed prefix */
#define WPA_EVENT_CONNECTED "CTRL-EVENT-CONNECTED "

#define WPA_EVENT_DISCONNECTED "CTRL-EVENT-DISCONNECTED "

#define WPA_EVENT_ASSOC_REJECT "CTRL-EVENT-ASSOC-REJECT "

#define WPA_EVENT_AUTH_REJECT "CTRL-EVENT-AUTH-REJECT "

#define WPA_EVENT_TERMINATING "CTRL-EVENT-TERMINATING "

#define WPA_EVENT_PASSWORD_CHANGED "CTRL-EVENT-PASSWORD-CHANGED "

#define WPA_EVENT_EAP_NOTIFICATION "CTRL-EVENT-EAP-NOTIFICATION "

#define WPA_EVENT_EAP_STARTED "CTRL-EVENT-EAP-STARTED "

#define WPA_EVENT_EAP_PROPOSED_METHOD "CTRL-EVENT-EAP-PROPOSED-METHOD "

#define WPA_EVENT_EAP_METHOD "CTRL-EVENT-EAP-METHOD "

#define WPA_EVENT_EAP_PEER_CERT "CTRL-EVENT-EAP-PEER-CERT "

#define WPA_EVENT_EAP_PEER_ALT "CTRL-EVENT-EAP-PEER-ALT "

#define WPA_EVENT_EAP_TLS_CERT_ERROR "CTRL-EVENT-EAP-TLS-CERT-ERROR "

#define WPA_EVENT_EAP_STATUS "CTRL-EVENT-EAP-STATUS "

#define WPA_EVENT_EAP_SUCCESS "CTRL-EVENT-EAP-SUCCESS "

#define WPA_EVENT_EAP_FAILURE "CTRL-EVENT-EAP-FAILURE "

#define WPA_EVENT_TEMP_DISABLED "CTRL-EVENT-SSID-TEMP-DISABLED "

#define WPA_EVENT_REENABLED "CTRL-EVENT-SSID-REENABLED "

#define WPA_EVENT_SCAN_STARTED "CTRL-EVENT-SCAN-STARTED "

#define WPA_EVENT_SCAN_RESULTS "CTRL-EVENT-SCAN-RESULTS "

#define WPA_EVENT_SCAN_FAILED "CTRL-EVENT-SCAN-FAILED "

#define WPA_EVENT_STATE_CHANGE "CTRL-EVENT-STATE-CHANGE "

#define WPA_EVENT_BSS_ADDED "CTRL-EVENT-BSS-ADDED "

#define WPA_EVENT_BSS_REMOVED "CTRL-EVENT-BSS-REMOVED "

#define WPA_EVENT_NETWORK_NOT_FOUND "CTRL-EVENT-NETWORK-NOT-FOUND "

#define WPA_EVENT_SIGNAL_CHANGE "CTRL-EVENT-SIGNAL-CHANGE "

#define WPA_EVENT_REGDOM_CHANGE "CTRL-EVENT-REGDOM-CHANGE "

#define IBSS_RSN_COMPLETED "IBSS-RSN-COMPLETED "

#define WPA_EVENT_FREQ_CONFLICT "CTRL-EVENT-FREQ-CONFLICT "

#define WPA_EVENT_AVOID_FREQ "CTRL-EVENT-AVOID-FREQ "

#define WPS_EVENT_OVERLAP "WPS-OVERLAP-DETECTED "

#define WPS_EVENT_AP_AVAILABLE_PBC "WPS-AP-AVAILABLE-PBC "

#define WPS_EVENT_AP_AVAILABLE_AUTH "WPS-AP-AVAILABLE-AUTH "

#define WPS_EVENT_AP_AVAILABLE_PIN "WPS-AP-AVAILABLE-PIN "

#define WPS_EVENT_AP_AVAILABLE "WPS-AP-AVAILABLE "

#define WPS_EVENT_CRED_RECEIVED "WPS-CRED-RECEIVED "

#define WPS_EVENT_M2D "WPS-M2D "

#define WPS_EVENT_FAIL "WPS-FAIL "

#define WPS_EVENT_SUCCESS "WPS-SUCCESS "

#define WPS_EVENT_TIMEOUT "WPS-TIMEOUT "
/* PBC mode was activated */
#define WPS_EVENT_ACTIVE "WPS-PBC-ACTIVE "
/* PBC mode was disabled */
#define WPS_EVENT_DISABLE "WPS-PBC-DISABLE "

#define WPS_EVENT_ENROLLEE_SEEN "WPS-ENROLLEE-SEEN "

#define WPS_EVENT_OPEN_NETWORK "WPS-OPEN-NETWORK "

/* WPS ER events */
#define WPS_EVENT_ER_AP_ADD "WPS-ER-AP-ADD "
#define WPS_EVENT_ER_AP_REMOVE "WPS-ER-AP-REMOVE "
#define WPS_EVENT_ER_ENROLLEE_ADD "WPS-ER-ENROLLEE-ADD "
#define WPS_EVENT_ER_ENROLLEE_REMOVE "WPS-ER-ENROLLEE-REMOVE "
#define WPS_EVENT_ER_AP_SETTINGS "WPS-ER-AP-SETTINGS "
#define WPS_EVENT_ER_SET_SEL_REG "WPS-ER-AP-SET-SEL-REG "

/* MESH events */
#define MESH_GROUP_STARTED "MESH-GROUP-STARTED "
#define MESH_GROUP_REMOVED "MESH-GROUP-REMOVED "
#define MESH_PEER_CONNECTED "MESH-PEER-CONNECTED "
#define MESH_PEER_DISCONNECTED "MESH-PEER-DISCONNECTED "

#define MESH_SAE_AUTH_FAILURE "MESH-SAE-AUTH-FAILURE "
#define MESH_SAE_AUTH_BLOCKED "MESH-SAE-AUTH-BLOCKED "

/* WMM AC events */
#define WMM_AC_EVENT_TSPEC_ADDED "TSPEC-ADDED "
#define WMM_AC_EVENT_TSPEC_REMOVED "TSPEC-REMOVED "
#define WMM_AC_EVENT_TSPEC_REQ_FAILED "TSPEC-REQ-FAILED "

#define P2P_EVENT_DEVICE_FOUND "P2P-DEVICE-FOUND "

#define P2P_EVENT_DEVICE_LOST "P2P-DEVICE-LOST "

#define P2P_EVENT_GO_NEG_REQUEST "P2P-GO-NEG-REQUEST "
#define P2P_EVENT_GO_NEG_SUCCESS "P2P-GO-NEG-SUCCESS "
#define P2P_EVENT_GO_NEG_FAILURE "P2P-GO-NEG-FAILURE "
#define P2P_EVENT_GROUP_FORMATION_SUCCESS "P2P-GROUP-FORMATION-SUCCESS "
#define P2P_EVENT_GROUP_FORMATION_FAILURE "P2P-GROUP-FORMATION-FAILURE "
#define P2P_EVENT_GROUP_STARTED "P2P-GROUP-STARTED "
#define P2P_EVENT_GROUP_REMOVED "P2P-GROUP-REMOVED "
#define P2P_EVENT_CROSS_CONNECT_ENABLE "P2P-CROSS-CONNECT-ENABLE "
#define P2P_EVENT_CROSS_CONNECT_DISABLE "P2P-CROSS-CONNECT-DISABLE "
/* parameters: <peer address> <PIN> */
#define P2P_EVENT_PROV_DISC_SHOW_PIN "P2P-PROV-DISC-SHOW-PIN "
/* parameters: <peer address> */
#define P2P_EVENT_PROV_DISC_ENTER_PIN "P2P-PROV-DISC-ENTER-PIN "
/* parameters: <peer address> */
#define P2P_EVENT_PROV_DISC_PBC_REQ "P2P-PROV-DISC-PBC-REQ "
/* parameters: <peer address> */
#define P2P_EVENT_PROV_DISC_PBC_RESP "P2P-PROV-DISC-PBC-RESP "
/* parameters: <peer address> <status> */
#define P2P_EVENT_PROV_DISC_FAILURE "P2P-PROV-DISC-FAILURE"
/* parameters: <freq> <src addr> <dialog token> <update indicator> <TLVs> */
#define P2P_EVENT_SERV_DISC_REQ "P2P-SERV-DISC-REQ "
/* parameters: <src addr> <update indicator> <TLVs> */
#define P2P_EVENT_SERV_DISC_RESP "P2P-SERV-DISC-RESP "
#define P2P_EVENT_SERV_ASP_RESP "P2P-SERV-ASP-RESP "
#define P2P_EVENT_INVITATION_RECEIVED "P2P-INVITATION-RECEIVED "
#define P2P_EVENT_INVITATION_RESULT "P2P-INVITATION-RESULT "
#define P2P_EVENT_FIND_STOPPED "P2P-FIND-STOPPED "
#define P2P_EVENT_PERSISTENT_PSK_FAIL "P2P-PERSISTENT-PSK-FAIL id="
#define P2P_EVENT_PRESENCE_RESPONSE "P2P-PRESENCE-RESPONSE "
#define P2P_EVENT_NFC_BOTH_GO "P2P-NFC-BOTH-GO "
#define P2P_EVENT_NFC_PEER_CLIENT "P2P-NFC-PEER-CLIENT "
#define P2P_EVENT_NFC_WHILE_CLIENT "P2P-NFC-WHILE-CLIENT "
#define P2P_EVENT_FALLBACK_TO_GO_NEG "P2P-FALLBACK-TO-GO-NEG "
#define P2P_EVENT_FALLBACK_TO_GO_NEG_ENABLED "P2P-FALLBACK-TO-GO-NEG-ENABLED "

/* parameters: <PMF enabled> <timeout in ms> <Session Information URL> */
#define ESS_DISASSOC_IMMINENT "ESS-DISASSOC-IMMINENT "
#define P2P_EVENT_REMOVE_AND_REFORM_GROUP "P2P-REMOVE-AND-REFORM-GROUP "

#define P2P_EVENT_P2PS_PROVISION_START "P2PS-PROV-START "
#define P2P_EVENT_P2PS_PROVISION_DONE "P2PS-PROV-DONE "

#define INTERWORKING_AP "INTERWORKING-AP "
#define INTERWORKING_BLACKLISTED "INTERWORKING-BLACKLISTED "
#define INTERWORKING_NO_MATCH "INTERWORKING-NO-MATCH "
#define INTERWORKING_ALREADY_CONNECTED "INTERWORKING-ALREADY-CONNECTED "
#define INTERWORKING_SELECTED "INTERWORKING-SELECTED "

/* Credential block added; parameters: <id> */
#define CRED_ADDED "CRED-ADDED "
/* Credential block modified; parameters: <id> <field> */
#define CRED_MODIFIED "CRED-MODIFIED "
/* Credential block removed; parameters: <id> */
#define CRED_REMOVED "CRED-REMOVED "

#define GAS_RESPONSE_INFO "GAS-RESPONSE-INFO "
/* parameters: <addr> <dialog_token> <freq> */
#define GAS_QUERY_START "GAS-QUERY-START "
/* parameters: <addr> <dialog_token> <freq> <status_code> <result> */
#define GAS_QUERY_DONE "GAS-QUERY-DONE "

/* parameters: <addr> <result> */
#define ANQP_QUERY_DONE "ANQP-QUERY-DONE "

#define HS20_SUBSCRIPTION_REMEDIATION "HS20-SUBSCRIPTION-REMEDIATION "
#define HS20_DEAUTH_IMMINENT_NOTICE "HS20-DEAUTH-IMMINENT-NOTICE "

#define EXT_RADIO_WORK_START "EXT-RADIO-WORK-START "
#define EXT_RADIO_WORK_TIMEOUT "EXT-RADIO-WORK-TIMEOUT "

#define RRM_EVENT_NEIGHBOR_REP_RXED "RRM-NEIGHBOR-REP-RECEIVED "
#define RRM_EVENT_NEIGHBOR_REP_FAILED "RRM-NEIGHBOR-REP-REQUEST-FAILED "

/* hostapd control interface - fixed message prefixes */
#define WPS_EVENT_PIN_NEEDED "WPS-PIN-NEEDED "
#define WPS_EVENT_NEW_AP_SETTINGS "WPS-NEW-AP-SETTINGS "
#define WPS_EVENT_REG_SUCCESS "WPS-REG-SUCCESS "
#define WPS_EVENT_AP_SETUP_LOCKED "WPS-AP-SETUP-LOCKED "
#define WPS_EVENT_AP_SETUP_UNLOCKED "WPS-AP-SETUP-UNLOCKED "
#define WPS_EVENT_AP_PIN_ENABLED "WPS-AP-PIN-ENABLED "
#define WPS_EVENT_AP_PIN_DISABLED "WPS-AP-PIN-DISABLED "
#define AP_STA_CONNECTED "AP-STA-CONNECTED "
#define AP_STA_DISCONNECTED "AP-STA-DISCONNECTED "
#define AP_STA_POSSIBLE_PSK_MISMATCH "AP-STA-POSSIBLE-PSK-MISMATCH "

#define AP_REJECTED_MAX_STA "AP-REJECTED-MAX-STA "
#define AP_REJECTED_BLOCKED_STA "AP-REJECTED-BLOCKED-STA "

#define AP_EVENT_ENABLED "AP-ENABLED "
#define AP_EVENT_DISABLED "AP-DISABLED "

#define INTERFACE_ENABLED "INTERFACE-ENABLED "
#define INTERFACE_DISABLED "INTERFACE-DISABLED "

#define ACS_EVENT_STARTED "ACS-STARTED "
#define ACS_EVENT_COMPLETED "ACS-COMPLETED "
#define ACS_EVENT_FAILED "ACS-FAILED "

#define DFS_EVENT_RADAR_DETECTED "DFS-RADAR-DETECTED "
#define DFS_EVENT_NEW_CHANNEL "DFS-NEW-CHANNEL "
#define DFS_EVENT_CAC_START "DFS-CAC-START "
#define DFS_EVENT_CAC_COMPLETED "DFS-CAC-COMPLETED "
#define DFS_EVENT_NOP_FINISHED "DFS-NOP-FINISHED "

#define AP_CSA_FINISHED "AP-CSA-FINISHED "

/* BSS Transition Management Response frame received */
#define BSS_TM_RESP "BSS-TM-RESP "

/* BSS command information masks */

#define WPA_BSS_MASK_ALL                0xFFFDFFFF
#define WPA_BSS_MASK_ID                 BIT(0)
#define WPA_BSS_MASK_BSSID              BIT(1)
#define WPA_BSS_MASK_FREQ               BIT(2)
#define WPA_BSS_MASK_BEACON_INT         BIT(3)
#define WPA_BSS_MASK_CAPABILITIES       BIT(4)
#define WPA_BSS_MASK_QUAL               BIT(5)
#define WPA_BSS_MASK_NOISE              BIT(6)
#define WPA_BSS_MASK_LEVEL              BIT(7)
#define WPA_BSS_MASK_TSF                BIT(8)
#define WPA_BSS_MASK_AGE                BIT(9)
#define WPA_BSS_MASK_IE                 BIT(10)
#define WPA_BSS_MASK_FLAGS              BIT(11)
#define WPA_BSS_MASK_SSID               BIT(12)
#define WPA_BSS_MASK_WPS_SCAN           BIT(13)
#define WPA_BSS_MASK_P2P_SCAN           BIT(14)
#define WPA_BSS_MASK_INTERNETW          BIT(15)
#define WPA_BSS_MASK_WIFI_DISPLAY       BIT(16)
#define WPA_BSS_MASK_DELIM              BIT(17)
#define WPA_BSS_MASK_MESH_SCAN          BIT(18)
#define WPA_BSS_MASK_SNR                BIT(19)
#define WPA_BSS_MASK_EST_THROUGHPUT     BIT(20)
#define WPA_BSS_MASK_FST                BIT(21)


/* VENDOR_ELEM_* frame id values */
enum wpa_vendor_elem_frame {
        VENDOR_ELEM_PROBE_REQ_P2P = 0,
        VENDOR_ELEM_PROBE_RESP_P2P = 1,
        VENDOR_ELEM_PROBE_RESP_P2P_GO = 2,
        VENDOR_ELEM_BEACON_P2P_GO = 3,
        VENDOR_ELEM_P2P_PD_REQ = 4,
        VENDOR_ELEM_P2P_PD_RESP = 5,
        VENDOR_ELEM_P2P_GO_NEG_REQ = 6,
        VENDOR_ELEM_P2P_GO_NEG_RESP = 7,
        VENDOR_ELEM_P2P_GO_NEG_CONF = 8,
        VENDOR_ELEM_P2P_INV_REQ = 9,
        VENDOR_ELEM_P2P_INV_RESP = 10,
        VENDOR_ELEM_P2P_ASSOC_REQ = 11,
        VENDOR_ELEM_P2P_ASSOC_RESP = 12,
        VENDOR_ELEM_ASSOC_REQ = 13,
        NUM_VENDOR_ELEM_FRAMES
};


/* wpa_supplicant/hostapd control interface access */

struct wpa_ctrl * wpa_ctrl_open(const char *ctrl_path);

struct wpa_ctrl * wpa_ctrl_open2(const char *ctrl_path, const char *cli_path);


void wpa_ctrl_close(struct wpa_ctrl *ctrl);


int wpa_ctrl_request(struct wpa_ctrl *ctrl, const char *cmd, size_t cmd_len,
                     char *reply, size_t *reply_len,
                     void (*msg_cb)(char *msg, size_t len));


int wpa_ctrl_attach(struct wpa_ctrl *ctrl);


int wpa_ctrl_detach(struct wpa_ctrl *ctrl);


int wpa_ctrl_recv(struct wpa_ctrl *ctrl, char *reply, size_t *reply_len);


int wpa_ctrl_pending(struct wpa_ctrl *ctrl);


int wpa_ctrl_get_fd(struct wpa_ctrl *ctrl);

#ifdef ANDROID

void wpa_ctrl_cleanup(void);
#endif /* ANDROID */

#ifdef CONFIG_CTRL_IFACE_UDP
/* Port range for multiple wpa_supplicant instances and multiple VIFs */
#define WPA_CTRL_IFACE_PORT 9877
#define WPA_CTRL_IFACE_PORT_LIMIT 50 /* decremented from start */
#define WPA_GLOBAL_CTRL_IFACE_PORT 9878
#define WPA_GLOBAL_CTRL_IFACE_PORT_LIMIT 20 /* incremented from start */

char * wpa_ctrl_get_remote_ifname(struct wpa_ctrl *ctrl);
#endif /* CONFIG_CTRL_IFACE_UDP */


#ifdef  __cplusplus
}
#endif


#endif // WPA_CTRL_H
